source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

"
" User defined
" Enable power of vim, compatible mode cripples it
set nocompatible
"
" Optimized for python development
set ts=4
set softtabstop=4
set shiftwidth=4
set textwidth=120
set smarttab
set expandtab
set ai
"
" Don't save backup files (~...)
" :set nobackup
"
" Change location of backup files (~...)
set backupdir-=.
set backupdir^=$TEMP
"
" Don't save undo files
set noundofile
"
" Don't auto-linewrap
set formatoptions-=t
"
" Default to using Tabs - this seems to cause problems:
"autocmd BufReadPost * tab ball
"
" Enable line numbers by default
set number
"
" Disable annoying auto-insert \n
set textwidth=0
"
" Interesting to note:
" set nowrap - disable line wrapping, have to scroll all the way to the right, useful in some circumstances

